// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	title: String;
	resumeButton: String;
	projects: String;
};

export type TranslationFunctions = {
	projects(): () => LocalizedString;
	resumeButton: () => LocalizedString;
	title: () => LocalizedString;
};

export type Formatters = {
	simpleDate: (value: Date) => unknown;
};
