// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​e​l​c​o​m​e​ ​|​ ​P​h​i​l​s​t​a​c​k​.​d​e​ ​-​ ​M​y​ ​W​e​b​-​D​e​v​e​l​o​p​e​r​ ​P​o​r​t​f​o​l​i​o
	 */
	title: string
	/**
	 * M​y​ ​P​r​o​j​e​c​t​s
	 */
	projectsTitle: string
	blogTitle: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contactTitle: string
	featuredTitle: string
	latestTitle: string
	popularTitle: string
	techstackTitle: string
	showcaseTitle: string
	skillsetTitle: string
	timelineTitle: string
	/**
	 * C​h​e​c​k​ ​o​u​t​ ​m​y​ ​R​e​s​u​m​e
	 */
	resumeButton: string
	/**
	 * V​i​e​w​ ​a​l​l​ ​P​r​o​j​e​c​t​s
	 */
	projectButton: string
	/**
	 * V​i​s​t​ ​B​l​o​g​p​a​g​e
	 */
	blogButton: string
	/**
	 * S​e​n​d​ ​M​e​s​s​a​g​e
	 */
	contactButton: string
	/**
	 * T​h​e​ ​K​r​e​a​t​i​v​W​e​r​k​s​t​a​t​t​ ​i​s​ ​a​ ​w​o​r​k​s​h​o​p​ ​f​o​r​ ​p​e​o​p​l​e​ ​w​i​t​h​ ​d​i​s​a​b​i​l​i​t​i​e​s​ ​(​W​f​b​M​)​ ​o​f​ ​L​e​b​e​n​s​h​i​l​f​e​ ​S​ü​d​-​T​h​u​r​i​n​g​i​a​.​ ​I​n​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​w​i​t​h​ ​t​h​e​m​,​ ​I​ ​c​r​e​a​t​e​d​ ​a​ ​p​h​o​t​o​ ​g​a​l​l​e​r​y​ ​f​o​r​ ​t​h​e​i​r​ ​u​n​i​q​u​e​ ​a​n​d​ ​b​e​a​u​t​i​f​u​l​ ​c​l​a​y​ ​a​n​d​ ​w​o​o​d​ ​p​r​o​d​u​c​t​s​ ​s​o​ ​t​h​a​t​ ​a​ ​t​a​b​l​e​t​ ​c​a​n​ ​b​e​ ​d​i​s​p​l​a​y​e​d​ ​i​n​ ​t​h​e​ ​e​n​t​r​a​n​c​e​ ​a​r​e​a​.​ ​T​h​i​s​ ​a​l​l​o​w​s​ ​c​u​s​t​o​m​e​r​s​ ​a​n​d​ ​v​i​s​i​t​o​r​s​ ​t​o​ ​v​i​e​w​ ​o​l​d​e​r​ ​p​r​o​d​u​c​t​s​ ​a​s​ ​w​e​l​l​,​ ​t​o​ ​p​o​s​s​i​b​l​y​ ​g​e​t​ ​i​n​s​p​i​r​e​d​ ​f​o​r​ ​t​h​e​i​r​ ​o​w​n​ ​o​r​d​e​r​s​.
	 */
	keaWeDescr: string
	/**
	 * D​u​e​ ​t​o​ ​m​y​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​ ​w​i​t​h​ ​K​r​e​a​t​i​v​W​e​r​k​s​t​a​t​t​ ​a​n​d​ ​t​h​e​ ​c​o​n​c​e​p​t​ ​f​o​r​ ​s​o​c​i​a​l​ ​m​e​d​i​a​,​ ​t​h​e​ ​l​a​b​e​l​i​n​g​ ​t​e​a​m​ ​a​p​p​r​o​a​c​h​e​d​ ​m​e​ ​a​n​d​ ​t​a​s​k​e​d​ ​m​e​ ​w​i​t​h​ ​c​r​e​a​t​i​n​g​ ​a​ ​p​r​o​m​o​t​i​o​n​a​l​ ​f​i​l​m​ ​f​o​r​ ​t​h​e​m​ ​a​n​d​ ​m​a​n​a​g​i​n​g​ ​t​h​e​i​r​ ​s​o​c​i​a​l​ ​m​e​d​i​a​ ​p​r​e​s​e​n​c​e​.​ ​A​d​d​i​t​i​o​n​a​l​l​y​,​ ​I​ ​w​a​s​ ​r​e​s​p​o​n​s​i​b​l​e​ ​f​o​r​ ​r​e​v​a​m​p​i​n​g​ ​t​h​e​i​r​ ​i​n​-​h​o​u​s​e​ ​w​e​b​s​i​t​e​ ​a​n​d​ ​o​p​t​i​m​i​z​i​n​g​ ​i​t​ ​f​o​r​ ​S​E​O​.
	 */
	beschrTeamDescr: string
	/**
	 * X​I​V​D​A​T​A​ ​i​s​ ​a​ ​p​r​o​j​e​c​t​ ​I​ ​j​o​i​n​e​d​ ​l​a​s​t​ ​y​e​a​r​,​ ​w​h​i​c​h​ ​w​i​l​l​ ​b​e​ ​a​ ​m​a​s​s​i​v​e​ ​d​a​t​a​b​a​s​e​ ​a​n​d​ ​t​o​o​l​ ​c​o​l​l​e​c​t​i​o​n​ ​f​o​r​ ​t​h​e​ ​s​u​c​c​e​s​s​f​u​l​ ​M​M​O​R​P​G​ ​"​F​i​n​a​l​ ​F​a​n​t​a​s​y​ ​X​I​V​"​ ​o​n​c​e​ ​i​t​ ​i​s​ ​c​o​m​p​l​e​t​e​d​.​ ​I​t​ ​i​s​ ​a​ ​h​o​b​b​y​ ​a​n​d​ ​s​i​d​e​ ​p​r​o​j​e​c​t​ ​w​i​t​h​ ​b​i​g​ ​a​m​b​i​t​i​o​n​s​ ​a​n​d​ ​t​h​e​r​e​f​o​r​e​ ​m​i​g​h​t​ ​t​a​k​e​ ​s​o​m​e​ ​t​i​m​e​ ​t​o​ ​c​o​m​p​l​e​t​e​.
	 */
	xivdataDesc: string
	/**
	 * M​a​r​c​e​l​ ​R​e​u​k​a​u​f​,​ ​t​h​e​ ​o​w​n​e​r​ ​o​f​ ​L​a​n​d​k​a​u​t​z​,​ ​a​p​p​r​o​a​c​h​e​d​ ​m​e​ ​a​t​ ​t​h​e​ ​e​n​d​ ​o​f​ ​2​0​2​2​ ​a​n​d​ ​a​s​k​e​d​ ​i​f​ ​I​ ​c​o​u​l​d​ ​c​r​e​a​t​e​ ​a​ ​n​e​w​ ​d​e​s​i​g​n​ ​f​o​r​ ​h​i​s​ ​e​m​e​r​g​i​n​g​ ​o​n​l​i​n​e​ ​s​h​o​p​.​ ​I​t​ ​w​a​s​ ​a​ ​S​h​o​p​i​f​y​ ​s​t​o​r​e​,​ ​w​h​i​c​h​ ​I​ ​h​a​d​ ​n​o​ ​p​r​i​o​r​ ​e​x​p​e​r​i​e​n​c​e​ ​w​i​t​h​.​ ​I​n​ ​a​d​d​i​t​i​o​n​ ​t​o​ ​t​h​e​ ​n​e​w​ ​d​e​s​i​g​n​,​ ​I​ ​a​l​s​o​ ​m​a​d​e​ ​s​o​m​e​ ​s​y​s​t​e​m​i​c​ ​a​d​j​u​s​t​m​e​n​t​s​ ​t​o​ ​t​h​e​ ​p​u​r​c​h​a​s​i​n​g​ ​a​n​d​ ​o​r​d​e​r​i​n​g​ ​p​r​o​c​e​s​s​.
	 */
	landkautzDescr: string
	/**
	 * v​i​e​w​ ​a​l​l​ ​p​r​o​j​e​c​t​s
	 */
	viewProjectsBtn: string
	posted: string
	author: string
	viewAll: string
	readMore: string
	job: string
	location: string
	articleAbout: string
	otherPosts: string
	fbShare: string
	xShare: string
	threadsShare: string
	linkShare: string
	dlPDF: string
	/**
	 * I​’​d​ ​l​o​v​e​ ​t​o​ ​h​e​a​r​ ​f​r​o​m​ ​y​o​u​.​ ​P​l​e​a​s​e​ ​f​i​l​l​ ​o​u​t​ ​t​h​i​s​ ​f​o​r​m​ ​o​r​ ​s​h​o​o​t​ ​u​s​ ​a​n​ ​m​a​i​l​!
	 */
	contactSub: string
	/**
	 * D​r​o​p​ ​a​ ​M​e​s​s​a​g​e​ ​i​n​ ​m​y​ ​I​n​b​o​x​ ​�​�
	 */
	mailText: string
	/**
	 * G​o​ ​f​o​r​ ​a​ ​C​a​l​l​!​ ​�​�
	 */
	phoneText: string
	/**
	 * H​i​t​ ​m​e​ ​u​p​ ​o​n​ ​W​h​a​t​s​a​p​p​!​ ​�​�
	 */
	whatsappText: string
	/**
	 * O​r​ ​j​u​s​t​ ​a​d​d​ ​m​e​ ​o​n​ ​D​i​s​c​o​r​d​ ​�​�
	 */
	discordText: string
	/**
	 * F​i​r​s​t​ ​N​a​m​e
	 */
	contacFirstname: string
	/**
	 * L​a​s​t​ ​N​a​m​e
	 */
	contacLastname: string
	/**
	 * E​m​a​i​l​ ​a​d​r​e​s​s
	 */
	contacMail: string
	/**
	 * Y​o​u​r​ ​M​e​s​s​a​g​e
	 */
	contactMessage: string
	back: string
	born: string
	/**
	 * o​n​l​y​ ​d​e​s​i​g​n​ ​&​ ​c​o​d​i​n​g​ ​r​e​l​a​t​e​d​ ​j​o​b​s​*
	 */
	timelineSub: string
}

export type TranslationFunctions = {
	/**
	 * Welcome | Philstack.de - My Web-Developer Portfolio
	 */
	title: () => LocalizedString
	/**
	 * My Projects
	 */
	projectsTitle: () => LocalizedString
	blogTitle: () => LocalizedString
	/**
	 * Contact
	 */
	contactTitle: () => LocalizedString
	featuredTitle: () => LocalizedString
	latestTitle: () => LocalizedString
	popularTitle: () => LocalizedString
	techstackTitle: () => LocalizedString
	showcaseTitle: () => LocalizedString
	skillsetTitle: () => LocalizedString
	timelineTitle: () => LocalizedString
	/**
	 * Check out my Resume
	 */
	resumeButton: () => LocalizedString
	/**
	 * View all Projects
	 */
	projectButton: () => LocalizedString
	/**
	 * Vist Blogpage
	 */
	blogButton: () => LocalizedString
	/**
	 * Send Message
	 */
	contactButton: () => LocalizedString
	/**
	 * The KreativWerkstatt is a workshop for people with disabilities (WfbM) of Lebenshilfe Süd-Thuringia. In collaboration with them, I created a photo gallery for their unique and beautiful clay and wood products so that a tablet can be displayed in the entrance area. This allows customers and visitors to view older products as well, to possibly get inspired for their own orders.
	 */
	keaWeDescr: () => LocalizedString
	/**
	 * Due to my collaboration with KreativWerkstatt and the concept for social media, the labeling team approached me and tasked me with creating a promotional film for them and managing their social media presence. Additionally, I was responsible for revamping their in-house website and optimizing it for SEO.
	 */
	beschrTeamDescr: () => LocalizedString
	/**
	 * XIVDATA is a project I joined last year, which will be a massive database and tool collection for the successful MMORPG "Final Fantasy XIV" once it is completed. It is a hobby and side project with big ambitions and therefore might take some time to complete.
	 */
	xivdataDesc: () => LocalizedString
	/**
	 * Marcel Reukauf, the owner of Landkautz, approached me at the end of 2022 and asked if I could create a new design for his emerging online shop. It was a Shopify store, which I had no prior experience with. In addition to the new design, I also made some systemic adjustments to the purchasing and ordering process.
	 */
	landkautzDescr: () => LocalizedString
	/**
	 * view all projects
	 */
	viewProjectsBtn: () => LocalizedString
	posted: () => LocalizedString
	author: () => LocalizedString
	viewAll: () => LocalizedString
	readMore: () => LocalizedString
	job: () => LocalizedString
	location: () => LocalizedString
	articleAbout: () => LocalizedString
	otherPosts: () => LocalizedString
	fbShare: () => LocalizedString
	xShare: () => LocalizedString
	threadsShare: () => LocalizedString
	linkShare: () => LocalizedString
	dlPDF: () => LocalizedString
	/**
	 * I’d love to hear from you. Please fill out this form or shoot us an mail!
	 */
	contactSub: () => LocalizedString
	/**
	 * Drop a Message in my Inbox 🤗
	 */
	mailText: () => LocalizedString
	/**
	 * Go for a Call! 👌
	 */
	phoneText: () => LocalizedString
	/**
	 * Hit me up on Whatsapp! 💪
	 */
	whatsappText: () => LocalizedString
	/**
	 * Or just add me on Discord 😊
	 */
	discordText: () => LocalizedString
	/**
	 * First Name
	 */
	contacFirstname: () => LocalizedString
	/**
	 * Last Name
	 */
	contacLastname: () => LocalizedString
	/**
	 * Email adress
	 */
	contacMail: () => LocalizedString
	/**
	 * Your Message
	 */
	contactMessage: () => LocalizedString
	back: () => LocalizedString
	born: () => LocalizedString
	/**
	 * only design & coding related jobs*
	 */
	timelineSub: () => LocalizedString
}

export type Formatters = {}
